name: sciview-update-sites-build
on:
  push:
    branches:
      - main
      - sciview-ageratum
      - sciview-buttercup
jobs:
  update-site-deploy:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '8'
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-          
      - run: ".travis/build.sh"
        env:
          UPDATE_SITE_USER: ${{ secrets.UPDATE_SITE_USER }}
          UPDATE_SITE_PASS: ${{ secrets.UPDATE_SITE_PASS }}
